tags = ["blog", "personal", "responsive", 'minimal', 'clean', "simple", "google analytics", "light",
    "multilingual", "syntax highlighting", "fast", "customizable", "minimalistic", "technical", "amp",
    "white", "disqus", "starter", "search"]

features = ["amp", "seo", "pwa", "responsive", "structured data", "toc", "related content", "service-worker", "shortcodes",
    "syntax highlighting", "tags", "social share", "search","math-ml"]

min_version = "0.72.0"

[author]
    name = "Robin Pourtaud"
    homepage = "/"
